name: "Main / Pull requests build"
on:
    pull_request:
        paths-ignore:
            - '.txt'
            - 'LICENSE'
            - 'docs/**'
        branches: [ main ]
    push:
        branches:
            - main

permissions:
    # required for all workflows
    security-events: write

    # required to fetch internal or private CodeQL packs
    packages: read

    # only required for workflows in private repositories
    actions: read
    contents: read
jobs:
    pre-commit:
        name: Pre-commit check
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout git repository
                uses: actions/checkout@v4.1.6
            -   name: Setup python
                uses: actions/setup-python@v5
                with:
                    python-version: "3.9"
            -   uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: '23'
            # -   name: Pre-commit checks
            #     uses: pre-commit/action@v3.0.1
            # -   name: pre-commit-c-lite
            #     uses: pre-commit-ci/lite-action@v1.1.0
            #     if: always()
    build:
        runs-on: ubuntu-latest
        needs: [ pre-commit ]
        strategy:
            fail-fast: true
            max-parallel: 1
        steps:
            -   uses: actions/checkout@v4.1.6
            -   name: Set up JDK 23
                uses: actions/setup-java@v4.2.1
                with:
                    distribution: 'temurin'
                    java-version: 23
                    architecture: x64
                    cache: 'maven'
            -   name: Build with Maven
                run: mvn --no-transfer-progress verify

    # Initializes the CodeQL tools for scanning.
            - name: Initialize CodeQL
              uses: github/codeql-action/init@v3
              with:
                languages: java-kotlin
                build-mode: none
                # If you wish to specify custom queries, you can do so here or in a config file.
                # By default, queries listed here will override any specified in a config file.
                # Prefix the list here with "+" to use these queries and those in the config file.

                # For more details on CodeQL's query packs, refer to: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
                #queries: security-extended,security-and-quality

            # If the analyze step fails for one of the languages you are analyzing with
            # "We were unable to automatically build your code", modify the matrix above
            # to set the build mode to "manual" for that language. Then modify this step
            # to build your code.
            # ℹ️ Command-line programs to run using the OS shell.
            # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
            ## - if: matrix.build-mode == 'manual'
            #   shell: bash
            #   run: |
            #     echo 'If you are using a "manual" build mode for one or more of the' \
            #       'languages you are analyzing, replace this with the commands to build' \
            #       'your code, for example:'
            #     echo '  make bootstrap'
            #     echo '  make release'
            #     exit 1

            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v3
              id: analyze
              with:
                category: "/language:java-kotlin"

            - name: Upload SARIF file
              uses: actions/upload-artifact@v4
              with:
                name: codeql-sarif-upload
                path: ${{ steps.analyze.outputs.sarif-output }}